version: 4.6.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: branch={branch},commit=$(APPVEYOR_REPO_COMMIT)
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
artifacts:
- path: _output\**\*.nupkg
  name: nupkg
- path: _output\**\*.snupkg
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: RwKwEk+5rBDbLmcZ2AgyRuCF1LO9GoXaZ2izhWBUlUREJdA2YKZgS4HHqXfPe0zm
  on:
    branch: master